spring:
  # Datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mild-db-1.czntvsqmhfmz.ap-northeast-2.rds.amazonaws.com:3306/mild?allowMultiQueries=true
    username: admin
    password: Passw0rd
  # JPA config
  jpa:
    properties:
      hibernate:
        # 데이터베이스 방언 설정
        #dialect: org.hibernate.dialect.MariaDBDialect
        dialect: mild.batch.config.CustomMariaDialect
        # 하이버네이트가 실행한 SQL을 출력
        show_sql: true
        # 출력한 SQL을 보기 쉽게 정렬
        format_sql: true
        # 주석도 함께 출력
        use_sql_comment: true

  # Batch config
#  batch:
#    jdbc:
#      initialize-schema: always
#    job:
#      enabled: false
